# General settings

start-at-login = true

# Accordion settings
accordion-padding = 0

# 'main' binding mode declaration.
[mode.main.binding]

# Application shortcuts
alt-enter = 'exec-and-forget open -n /Applications/Alacritty.app'
# Window navigation (Vim-style):

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Window management

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Layout management

alt-t = 'layout tiles accordion'

alt-shift-u = 'resize smart -50'
alt-shift-i = 'resize smart +50'

# Workspace management

alt-tab = 'workspace-back-and-forth'

# defining a binding to switch to the 'service' binding mode
alt-shift-ctrl-k= 'mode service'

# Workspace assignment

alt-a = 'workspace 1'
alt-s = 'workspace 2'
alt-d = 'workspace 3'
alt-f = 'workspace 4'
alt-g = 'workspace 5'
alt-z = 'workspace 6'
alt-x = 'workspace 7'
alt-c = 'workspace 8'
alt-v = 'workspace 9'

alt-shift-a = 'move-node-to-workspace 1'
alt-shift-s = 'move-node-to-workspace 2'
alt-shift-d = 'move-node-to-workspace 3'
alt-shift-f = 'move-node-to-workspace 4'
alt-shift-g = 'move-node-to-workspace 5'
alt-shift-z = 'move-node-to-workspace 6'
alt-shift-x = 'move-node-to-workspace 7'
alt-shift-c = 'move-node-to-workspace 8'
alt-shift-v = 'move-node-to-workspace 9'

alt-ctrl-h = ['join-with left', 'mode main']
alt-ctrl-j = ['join-with down', 'mode main']
alt-ctrl-k = ['join-with up', 'mode main']
alt-ctrl-l = ['join-with right', 'mode main']

# Terminal Emulator
[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 1'

# IDE
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 2'

# Web browser
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 3'

# 'service' binding mode declaration.
[mode.service.binding]

r = ['reload-config', 'mode main']
f = ['flatten-workspace-tree', 'mode main'] # reset layout
l = ['layout floating tiling', 'mode main'] # between floating and tiling layout
q = ['close-all-windows-but-current', 'mode main']
esc = 'mode main'
