#!/bin/bash

# Function to disable Finder features
configure_finder() {
    echo "Configuring Finder settings..."

    defaults write com.apple.finder CreateDesktop -bool false
    defaults write com.apple.finder ShowRecentTags -bool false
    defaults write com.apple.finder WarnOnEmptyTrash -bool false
    defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
    defaults write com.apple.finder "ShowExternalHardDrivesOnDesktop" -bool false
    defaults write com.apple.finder "ShowRemovableMediaOnDesktop" -bool false
    defaults write com.apple.finder "ShowMountedServersOnDesktop" -bool false
    defaults write com.apple.finder UseStacks -bool false

    defaults write com.apple.finder "QuitMenuItem" -bool true
    defaults write com.apple.finder "AppleShowAllFiles" -bool true
    defaults write com.apple.finder "_FXSortFoldersFirst" -bool true
    defaults write com.apple.finder DisableAllAnimations -bool true
    defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
    defaults write com.apple.finder ShowPathbar -bool true
    defaults write com.apple.finder ShowStatusBar -bool true
    defaults write com.apple.finder QLInlinePreviewVisibleOnlyInColumnView -bool true
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
    defaults write com.apple.finder QLEnableTextSelection -bool true

    defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
    defaults write com.apple.finder NewWindowTarget -string "PfLo"
    defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"
    defaults write com.apple.finder "FXDefaultSearchScope" -string "SCcf"
    
    echo "Dock settings configured."

    # Restart Finder to apply changes
    killall Finder
}

# Run the Finder configuration function
configure_finger

echo "Finder configuration script executed successfully."
