#!/bin/bash

# Function to disable trackpad gestures
configure_trackpad() {
    echo "Disabling trackpad gestures..."

    defaults write com.apple.AppleMultitouchTrackpad TrackpadMomentumScroll -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadPinch -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadRotate -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadCornerSecondaryClick -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadFiveFingerPinchGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerHorizSwipeGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerPinchGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadFourFingerVertSwipeGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerHorizSwipeGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerVertSwipeGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerTapGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadTwoFingerDoubleTapGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadTwoFingerFromRightEdgeSwipeGesture -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool false
    defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -bool false
    defaults write com.apple.AppleMultitouchTrackpad TrackpadHorizScroll -bool false
    defaults write com.apple.AppleMultitouchTrackpad USBMouseStopsTrackpad -bool false

    defaults write com.apple.AppleMultitouchTrackpad TrackpadScroll -bool true
    defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

    echo "Trackpad gestures disabled."

    # Restart Trackpad to apply changes
    killall "System Preferences" 2>/dev/null
}


# Run the Trackpad configuration function
configure_trackpad

echo "Trackpad configuration script executed successfully."
